name: 'Auto Assign Copilot'
on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Copilot
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          assignees: 'copilot'
          github-token: '${{ secrets.MY_PAT }}'
